CREATE TABLE public.message_conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_low_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  participant_high_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz,
  last_message_body text,
  last_message_sender_id integer REFERENCES public.users(id) ON DELETE SET NULL,
  unread_low integer NOT NULL DEFAULT 0 CHECK (unread_low >= 0),
  unread_high integer NOT NULL DEFAULT 0 CHECK (unread_high >= 0),
  CONSTRAINT message_conversations_sorted_participants CHECK (participant_low_id < participant_high_id),
  CONSTRAINT message_conversations_unique_pair UNIQUE (participant_low_id, participant_high_id)
);

CREATE INDEX idx_message_conversations_low_recent
  ON public.message_conversations (participant_low_id, last_message_at DESC NULLS LAST, id DESC);
CREATE INDEX idx_message_conversations_high_recent
  ON public.message_conversations (participant_high_id, last_message_at DESC NULLS LAST, id DESC);

CREATE TABLE public.direct_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES public.message_conversations(id) ON DELETE CASCADE,
  sender_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  body text NOT NULL CHECK (length(btrim(body)) BETWEEN 1 AND 2000),
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz
);

CREATE INDEX idx_direct_messages_history
  ON public.direct_messages (conversation_id, id DESC);
CREATE INDEX idx_direct_messages_unread
  ON public.direct_messages (conversation_id, sender_user_id)
  WHERE read_at IS NULL;

ALTER TABLE public.message_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.message_conversations, public.direct_messages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.message_conversations, public.direct_messages TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.message_conversations_id_seq, public.direct_messages_id_seq TO service_role;

CREATE FUNCTION public.direct_message_contact_ids(p_user_id integer)
RETURNS TABLE(contact_user_id integer)
LANGUAGE sql
SECURITY INVOKER
SET search_path = ''
AS $$
  WITH contacts AS (
    -- Riders can contact captains assigned to one of their pool groups.
    SELECT trip.captain_user_id AS user_id
    FROM public.pool_members member
    JOIN public.pool_trips trip ON trip.group_id = member.group_id
    WHERE member.rider_user_id = p_user_id
      AND member.status <> 'cancelled'
      AND trip.captain_user_id IS NOT NULL
    UNION
    SELECT group_row.fixed_captain_user_id
    FROM public.pool_members member
    JOIN public.pool_groups group_row ON group_row.id = member.group_id
    WHERE member.rider_user_id = p_user_id
      AND member.status <> 'cancelled'
      AND group_row.fixed_captain_user_id IS NOT NULL
    UNION
    -- Captains can contact riders on the groups they serve.
    SELECT member.rider_user_id
    FROM public.pool_trips trip
    JOIN public.pool_members member ON member.group_id = trip.group_id
    WHERE trip.captain_user_id = p_user_id
      AND member.status <> 'cancelled'
    UNION
    -- A matched daily ride links its rider and captain.
    SELECT matched_ride.captain_user_id
    FROM public.daily_commute_requests request
    JOIN public.matches matched_ride ON matched_ride.daily_commute_request_id = request.id
    WHERE request.rider_user_id = p_user_id
    UNION
    SELECT request.rider_user_id
    FROM public.matches matched_ride
    JOIN public.daily_commute_requests request ON request.id = matched_ride.daily_commute_request_id
    WHERE matched_ride.captain_user_id = p_user_id
  )
  SELECT DISTINCT contacts.user_id
  FROM contacts
  JOIN public.users contact ON contact.id = contacts.user_id
  WHERE contacts.user_id <> p_user_id
    AND contact.role IN ('rider', 'captain');
$$;
REVOKE ALL ON FUNCTION public.direct_message_contact_ids(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.direct_message_contact_ids(integer) TO service_role;

CREATE FUNCTION public.send_direct_message(p_sender_user_id integer, p_conversation_id bigint, p_body text)
RETURNS TABLE(id bigint, conversation_id bigint, sender_user_id integer, body text, created_at timestamptz, read_at timestamptz)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  conversation_row public.message_conversations;
  inserted_message public.direct_messages;
  recipient_user_id integer;
BEGIN
  IF p_body IS NULL OR length(btrim(p_body)) NOT BETWEEN 1 AND 2000 THEN
    RAISE EXCEPTION 'invalid message body' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO conversation_row
  FROM public.message_conversations
  WHERE id = p_conversation_id
    AND p_sender_user_id IN (participant_low_id, participant_high_id)
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'conversation not found' USING ERRCODE = '42501';
  END IF;

  recipient_user_id := CASE
    WHEN p_sender_user_id = conversation_row.participant_low_id THEN conversation_row.participant_high_id
    ELSE conversation_row.participant_low_id
  END;

  INSERT INTO public.direct_messages (conversation_id, sender_user_id, body)
  VALUES (p_conversation_id, p_sender_user_id, btrim(p_body))
  RETURNING * INTO inserted_message;

  UPDATE public.message_conversations
  SET last_message_at = inserted_message.created_at,
      last_message_body = inserted_message.body,
      last_message_sender_id = p_sender_user_id,
      unread_low = unread_low + CASE WHEN recipient_user_id = participant_low_id THEN 1 ELSE 0 END,
      unread_high = unread_high + CASE WHEN recipient_user_id = participant_high_id THEN 1 ELSE 0 END
  WHERE id = p_conversation_id;

  RETURN QUERY SELECT inserted_message.id, inserted_message.conversation_id,
    inserted_message.sender_user_id, inserted_message.body,
    inserted_message.created_at, inserted_message.read_at;
END;
$$;
REVOKE ALL ON FUNCTION public.send_direct_message(integer, bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.send_direct_message(integer, bigint, text) TO service_role;

CREATE FUNCTION public.mark_direct_messages_read(p_user_id integer, p_conversation_id bigint)
RETURNS integer
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  conversation_row public.message_conversations;
  updated_count integer;
BEGIN
  SELECT * INTO conversation_row
  FROM public.message_conversations
  WHERE id = p_conversation_id
    AND p_user_id IN (participant_low_id, participant_high_id)
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'conversation not found' USING ERRCODE = '42501';
  END IF;

  UPDATE public.direct_messages
  SET read_at = now()
  WHERE conversation_id = p_conversation_id
    AND sender_user_id <> p_user_id
    AND read_at IS NULL;
  GET DIAGNOSTICS updated_count = ROW_COUNT;

  UPDATE public.message_conversations
  SET unread_low = CASE WHEN p_user_id = participant_low_id THEN 0 ELSE unread_low END,
      unread_high = CASE WHEN p_user_id = participant_high_id THEN 0 ELSE unread_high END
  WHERE id = p_conversation_id;

  RETURN updated_count;
END;
$$;
REVOKE ALL ON FUNCTION public.mark_direct_messages_read(integer, bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mark_direct_messages_read(integer, bigint) TO service_role;
