-- Captain-published route offers and rider demand clustering.
-- Existing ride/group records remain intact; this adds the PRD flow alongside them.

CREATE TABLE public.app_config (
  config_key text PRIMARY KEY,
  numeric_value numeric NOT NULL CHECK (numeric_value > 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.app_config(config_key, numeric_value) VALUES
  ('demand_route_radius_km', 2.5),
  ('demand_arrival_window_minutes', 15);

CREATE TABLE public.captain_lines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captain_user_id integer NOT NULL REFERENCES public.users(id),
  vehicle_type_id text NOT NULL REFERENCES public.vehicle_types(id),
  origin_label text NOT NULL CHECK (length(btrim(origin_label)) BETWEEN 2 AND 240),
  origin_lat double precision NOT NULL CHECK (origin_lat BETWEEN -90 AND 90),
  origin_lng double precision NOT NULL CHECK (origin_lng BETWEEN -180 AND 180),
  destination_label text NOT NULL CHECK (length(btrim(destination_label)) BETWEEN 2 AND 240),
  destination_lat double precision NOT NULL CHECK (destination_lat BETWEEN -90 AND 90),
  destination_lng double precision NOT NULL CHECK (destination_lng BETWEEN -180 AND 180),
  intermediate_stops jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(intermediate_stops) = 'array'),
  arrival_time time NOT NULL,
  service_days smallint[] NOT NULL CHECK (cardinality(service_days) BETWEEN 1 AND 7 AND service_days <@ ARRAY[0,1,2,3,4,5,6]::smallint[]),
  seats integer NOT NULL CHECK (seats BETWEEN 1 AND 14),
  price_per_seat numeric(10,2) NOT NULL CHECK (price_per_seat >= 0),
  payment_methods text[] NOT NULL DEFAULT ARRAY['cash']::text[] CHECK (cardinality(payment_methods) > 0 AND payment_methods <@ ARRAY['cash','instapay','wallet']::text[]),
  women_only boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX captain_lines_search_idx ON public.captain_lines(vehicle_type_id, status, arrival_time);
CREATE INDEX captain_lines_captain_idx ON public.captain_lines(captain_user_id, created_at DESC);

CREATE TABLE public.demand_groups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_type_id text NOT NULL REFERENCES public.vehicle_types(id),
  origin_lat double precision NOT NULL CHECK (origin_lat BETWEEN -90 AND 90),
  origin_lng double precision NOT NULL CHECK (origin_lng BETWEEN -180 AND 180),
  destination_lat double precision NOT NULL CHECK (destination_lat BETWEEN -90 AND 90),
  destination_lng double precision NOT NULL CHECK (destination_lng BETWEEN -180 AND 180),
  trip_date date NOT NULL,
  arrival_time time NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','matched','expired','cancelled')),
  captain_line_id integer REFERENCES public.captain_lines(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX demand_groups_match_idx ON public.demand_groups(vehicle_type_id, trip_date, arrival_time) WHERE status = 'open';

CREATE TABLE public.demand_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_user_id integer NOT NULL REFERENCES public.users(id),
  demand_group_id integer REFERENCES public.demand_groups(id),
  vehicle_type_id text NOT NULL REFERENCES public.vehicle_types(id),
  trip_date date NOT NULL,
  arrival_time time NOT NULL,
  pickup_label text NOT NULL CHECK (length(btrim(pickup_label)) BETWEEN 2 AND 240),
  pickup_lat double precision NOT NULL CHECK (pickup_lat BETWEEN -90 AND 90),
  pickup_lng double precision NOT NULL CHECK (pickup_lng BETWEEN -180 AND 180),
  dropoff_label text NOT NULL CHECK (length(btrim(dropoff_label)) BETWEEN 2 AND 240),
  dropoff_lat double precision NOT NULL CHECK (dropoff_lat BETWEEN -90 AND 90),
  dropoff_lng double precision NOT NULL CHECK (dropoff_lng BETWEEN -180 AND 180),
  seats integer NOT NULL DEFAULT 1 CHECK (seats BETWEEN 1 AND 14),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','matched','cancelled','expired')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(rider_user_id, demand_group_id)
);
CREATE INDEX demand_requests_rider_idx ON public.demand_requests(rider_user_id, created_at DESC);
CREATE INDEX demand_requests_group_idx ON public.demand_requests(demand_group_id, status);
CREATE TRIGGER trg_demand_requests_rider_role BEFORE INSERT OR UPDATE OF rider_user_id ON public.demand_requests
FOR EACH ROW EXECUTE FUNCTION public.sekka_require_role('rider_user_id','rider');

ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.captain_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.app_config, public.captain_lines, public.demand_groups, public.demand_requests FROM anon, authenticated;
GRANT ALL ON public.app_config, public.captain_lines, public.demand_groups, public.demand_requests TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.captain_lines_id_seq, public.demand_groups_id_seq, public.demand_requests_id_seq TO service_role;
CREATE OR REPLACE FUNCTION public.sekka_geo_km(lat_a double precision, lng_a double precision, lat_b double precision, lng_b double precision)
RETURNS double precision LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$
  SELECT 6371 * 2 * asin(sqrt(
    power(sin(radians(lat_b-lat_a)/2),2) +
    cos(radians(lat_a))*cos(radians(lat_b))*power(sin(radians(lng_b-lng_a)/2),2)
  ))
$$;

CREATE OR REPLACE FUNCTION public.sekka_match_demand_group(group_id integer) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE demand public.demand_groups%ROWTYPE; line public.captain_lines%ROWTYPE; radius_km numeric; time_window numeric;
        group_seats integer; occupied_seats integer;
BEGIN
  SELECT * INTO demand FROM public.demand_groups WHERE id=group_id AND status='open' FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT numeric_value INTO radius_km FROM public.app_config WHERE config_key='demand_route_radius_km';
  SELECT numeric_value INTO time_window FROM public.app_config WHERE config_key='demand_arrival_window_minutes';
  SELECT * INTO line FROM public.captain_lines l
   WHERE l.status='active' AND l.vehicle_type_id=demand.vehicle_type_id
     AND extract(dow FROM demand.trip_date)::smallint = ANY(l.service_days)
     AND least(abs(extract(epoch FROM (l.arrival_time-demand.arrival_time))/60), 1440-abs(extract(epoch FROM (l.arrival_time-demand.arrival_time))/60)) <= time_window
     AND public.sekka_geo_km(l.origin_lat,l.origin_lng,demand.origin_lat,demand.origin_lng) <= radius_km
     AND public.sekka_geo_km(l.destination_lat,l.destination_lng,demand.destination_lat,demand.destination_lng) <= radius_km
   ORDER BY public.sekka_geo_km(l.origin_lat,l.origin_lng,demand.origin_lat,demand.origin_lng)+public.sekka_geo_km(l.destination_lat,l.destination_lng,demand.destination_lat,demand.destination_lng), l.id
   LIMIT 1;
  IF FOUND THEN
    PERFORM 1 FROM public.captain_lines WHERE id=line.id FOR UPDATE;
    SELECT * INTO line FROM public.captain_lines WHERE id=line.id AND status='active';
    IF NOT FOUND THEN RETURN; END IF;
    SELECT coalesce(sum(seats),0)::integer INTO group_seats FROM public.demand_requests WHERE demand_group_id=demand.id AND status='open';
    SELECT coalesce(sum(r.seats),0)::integer INTO occupied_seats
      FROM public.demand_groups g JOIN public.demand_requests r ON r.demand_group_id=g.id
      WHERE g.captain_line_id=line.id AND g.trip_date=demand.trip_date AND g.status='matched';
    IF group_seats + occupied_seats > line.seats THEN RETURN; END IF;
    UPDATE public.demand_groups SET status='matched', captain_line_id=line.id WHERE id=demand.id AND status='open';
    UPDATE public.demand_requests SET status='matched' WHERE demand_group_id=demand.id AND status='open';
    INSERT INTO public.pool_notifications(user_id,group_id,event_key,payload)
      SELECT r.rider_user_id,NULL,'demand-match:'||r.id,jsonb_build_object('title','تم العثور على مسار مناسب','message','تم ربط طلبك بمسار مناسب. افتح التطبيق لمراجعة التفاصيل.','line_id',line.id)
      FROM public.demand_requests r WHERE r.demand_group_id=demand.id
      ON CONFLICT(user_id,event_key) DO NOTHING;
    INSERT INTO public.pool_notifications(user_id,group_id,event_key,payload)
      VALUES(line.captain_user_id,NULL,'captain-line-demand:'||line.id||':'||demand.id,jsonb_build_object('title','طلبات ركاب جديدة','message','تم تجميع طلبات ركاب متشابهة على مسارك.','demand_group_id',demand.id))
      ON CONFLICT(user_id,event_key) DO NOTHING;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.sekka_cluster_demand_request() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE selected_group integer; radius_km numeric; time_window numeric; group_status text; matched_line_id integer; line_capacity integer; existing_seats integer;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(NEW.vehicle_type_id), NEW.trip_date - DATE '2000-01-01');
  SELECT numeric_value INTO radius_km FROM public.app_config WHERE config_key='demand_route_radius_km';
  SELECT numeric_value INTO time_window FROM public.app_config WHERE config_key='demand_arrival_window_minutes';
  SELECT g.id INTO selected_group FROM public.demand_groups g
   WHERE g.status IN ('open','matched') AND g.vehicle_type_id=NEW.vehicle_type_id
     AND g.trip_date=NEW.trip_date
     AND least(abs(extract(epoch FROM (g.arrival_time-NEW.arrival_time))/60), 1440-abs(extract(epoch FROM (g.arrival_time-NEW.arrival_time))/60)) <= time_window
     AND public.sekka_geo_km(g.origin_lat,g.origin_lng,NEW.pickup_lat,NEW.pickup_lng) <= radius_km
     AND public.sekka_geo_km(g.destination_lat,g.destination_lng,NEW.dropoff_lat,NEW.dropoff_lng) <= radius_km
     AND (g.status='open' OR EXISTS (
       SELECT 1 FROM public.captain_lines l WHERE l.id=g.captain_line_id AND l.status='active'
        AND coalesce((SELECT sum(r.seats) FROM public.demand_requests r WHERE r.demand_group_id=g.id AND r.status IN ('open','matched')),0)+NEW.seats <= l.seats
     ))
   ORDER BY g.created_at, g.id LIMIT 1 FOR UPDATE OF g;
  IF selected_group IS NOT NULL THEN
    SELECT status,captain_line_id INTO group_status,matched_line_id FROM public.demand_groups WHERE id=selected_group;
    IF group_status='matched' THEN
      SELECT seats INTO line_capacity FROM public.captain_lines WHERE id=matched_line_id AND status='active';
      SELECT coalesce(sum(seats),0)::integer INTO existing_seats FROM public.demand_requests WHERE demand_group_id=selected_group AND status IN ('open','matched');
      IF existing_seats + NEW.seats > coalesce(line_capacity,0) THEN selected_group := NULL; END IF;
    END IF;
  END IF;
  IF selected_group IS NULL THEN
    INSERT INTO public.demand_groups(vehicle_type_id,origin_lat,origin_lng,destination_lat,destination_lng,trip_date,arrival_time)
    VALUES(NEW.vehicle_type_id,NEW.pickup_lat,NEW.pickup_lng,NEW.dropoff_lat,NEW.dropoff_lng,NEW.trip_date,NEW.arrival_time)
    RETURNING id INTO selected_group;
  END IF;
  NEW.demand_group_id := selected_group;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_demand_requests_cluster BEFORE INSERT ON public.demand_requests
FOR EACH ROW EXECUTE FUNCTION public.sekka_cluster_demand_request();

CREATE OR REPLACE FUNCTION public.sekka_match_after_demand_insert() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
  PERFORM public.sekka_match_demand_group(NEW.demand_group_id);
  RETURN NEW;
END $$;
CREATE TRIGGER trg_demand_requests_match AFTER INSERT ON public.demand_requests
FOR EACH ROW EXECUTE FUNCTION public.sekka_match_after_demand_insert();

CREATE OR REPLACE FUNCTION public.sekka_match_after_line_publish() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE demand_row record;
BEGIN
  IF NEW.status='active' THEN
    FOR demand_row IN SELECT id FROM public.demand_groups WHERE status='open' AND vehicle_type_id=NEW.vehicle_type_id
      AND extract(dow FROM trip_date)::smallint = ANY(NEW.service_days)
    LOOP
      PERFORM public.sekka_match_demand_group(demand_row.id);
    END LOOP;
  END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.publish_captain_line(
  actor_id integer, vehicle_id text, origin_name text, origin_y double precision, origin_x double precision,
  destination_name text, destination_y double precision, destination_x double precision, stops jsonb,
  arrival time, days smallint[], seat_count integer, seat_price numeric, methods text[]
) RETURNS public.captain_lines
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog, public AS $$
DECLARE created public.captain_lines%ROWTYPE;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id=actor_id AND role='captain' AND verified_at IS NOT NULL) THEN
    RAISE EXCEPTION 'verified captain required' USING ERRCODE='42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.captain_profiles WHERE user_id=actor_id AND verification_status='approved' AND vehicle_type_id=vehicle_id) THEN
    RAISE EXCEPTION 'approved vehicle profile required' USING ERRCODE='42501';
  END IF;
  INSERT INTO public.captain_lines(captain_user_id,vehicle_type_id,origin_label,origin_lat,origin_lng,destination_label,destination_lat,destination_lng,intermediate_stops,arrival_time,service_days,seats,price_per_seat,payment_methods)
  VALUES(actor_id,vehicle_id,origin_name,origin_y,origin_x,destination_name,destination_y,destination_x,coalesce(stops,'[]'::jsonb),arrival,days,seat_count,seat_price,methods)
  RETURNING * INTO created;
  RETURN created;
END $$;
CREATE TRIGGER trg_captain_line_match AFTER INSERT OR UPDATE OF status ON public.captain_lines
FOR EACH ROW EXECUTE FUNCTION public.sekka_match_after_line_publish();

CREATE OR REPLACE FUNCTION public.create_demand_request(
  actor_id integer, vehicle_id text, trip_on date, arrives time,
  pickup_name text, pickup_y double precision, pickup_x double precision,
  dropoff_name text, dropoff_y double precision, dropoff_x double precision, seat_count integer DEFAULT 1
) RETURNS public.demand_requests
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog, public AS $$
DECLARE created public.demand_requests%ROWTYPE;
BEGIN
  IF trip_on < (now() AT TIME ZONE 'Africa/Cairo')::date THEN RAISE EXCEPTION 'trip date must be today or later' USING ERRCODE='22023'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id=actor_id AND role='rider' AND verified_at IS NOT NULL) THEN
    RAISE EXCEPTION 'verified rider required' USING ERRCODE='42501';
  END IF;
  INSERT INTO public.demand_requests(rider_user_id,vehicle_type_id,trip_date,arrival_time,pickup_label,pickup_lat,pickup_lng,dropoff_label,dropoff_lat,dropoff_lng,seats)
  VALUES(actor_id,vehicle_id,trip_on,arrives,pickup_name,pickup_y,pickup_x,dropoff_name,dropoff_y,dropoff_x,seat_count)
  RETURNING * INTO created;
  RETURN created;
END $$;

CREATE OR REPLACE FUNCTION public.set_captain_line_status(actor_id integer, line_id integer, next_status text)
RETURNS public.captain_lines
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog, public AS $$
DECLARE updated public.captain_lines%ROWTYPE;
BEGIN
  IF next_status NOT IN ('active','paused','cancelled') THEN RAISE EXCEPTION 'invalid status' USING ERRCODE='22023'; END IF;
  UPDATE public.captain_lines SET status=next_status, updated_at=now()
   WHERE id=line_id AND captain_user_id=actor_id AND EXISTS (
     SELECT 1 FROM public.users u JOIN public.captain_profiles c ON c.user_id=u.id
      WHERE u.id=actor_id AND u.role='captain' AND u.verified_at IS NOT NULL
        AND c.verification_status='approved' AND c.status <> 'suspended_grace_expired'
   )
   RETURNING * INTO updated;
  IF NOT FOUND THEN RAISE EXCEPTION 'line not found or not owned by captain' USING ERRCODE='42501'; END IF;
  RETURN updated;
END $$;

REVOKE ALL ON FUNCTION public.publish_captain_line(integer,text,text,double precision,double precision,text,double precision,double precision,jsonb,time,smallint[],integer,numeric,text[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.create_demand_request(integer,text,date,time,text,double precision,double precision,text,double precision,double precision,integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_captain_line_status(integer,integer,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.sekka_match_demand_group(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.publish_captain_line(integer,text,text,double precision,double precision,text,double precision,double precision,jsonb,time,smallint[],integer,numeric,text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_demand_request(integer,text,date,time,text,double precision,double precision,text,double precision,double precision,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_captain_line_status(integer,integer,text) TO service_role;
