-- Extend the existing private document-review table used by the app.
-- The API uses SeKKa's custom session tokens, so all metadata and signed URL
-- creation remain server-mediated through service_role; no client RLS policy
-- can safely map those custom sessions to auth.uid().
CREATE TABLE IF NOT EXISTS public.user_verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  document_type text NOT NULL CHECK (document_type IN (
    'national_id_front', 'national_id_back',
    'driving_license_front', 'driving_license_back',
    'vehicle_license_front', 'vehicle_license_back',
    'criminal_record', 'drug_test'
  )),
  status text NOT NULL DEFAULT 'pending',
  object_path text NOT NULL CHECK (char_length(object_path) BETWEEN 1 AND 512),
  content_type text NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')),
  file_size_bytes integer NOT NULL CHECK (file_size_bytes BETWEEN 1 AND 8388608),
  rejection_reason text CHECK (rejection_reason IS NULL OR char_length(rejection_reason) <= 1000),
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by integer REFERENCES public.users(id) ON DELETE SET NULL,
  UNIQUE (user_id, document_type)
);

-- Permit a temporary upload state so interrupted uploads cannot be reviewed.
ALTER TABLE public.user_verifications DROP CONSTRAINT IF EXISTS user_verifications_status_check;
ALTER TABLE public.user_verifications
  ADD CONSTRAINT user_verifications_status_check
  CHECK (status IN ('awaiting_upload', 'pending', 'approved', 'rejected'));

CREATE UNIQUE INDEX IF NOT EXISTS user_verifications_object_path_key
  ON public.user_verifications(object_path);
CREATE INDEX IF NOT EXISTS idx_user_verifications_review_queue
  ON public.user_verifications(status, uploaded_at ASC)
  WHERE status = 'pending';

ALTER TABLE public.user_verifications ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.user_verifications FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.user_verifications TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.user_verifications_id_seq TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('identity-documents', 'identity-documents', false, 8388608, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = 8388608,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp'];

-- Do not add direct anon/authenticated policies to storage.objects. Upload and read
-- access is mediated by signed URLs issued only after checking the app session.
