-- SeKKa PostgreSQL baseline (reviewed conversion of SQLite migrations 001–013).
-- Project was verified empty before this additive migration. DDL is applied atomically.
-- All API access is mediated by the Edge Function. Public roles receive no table grants.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL CHECK (length(btrim(full_name)) > 0),
  phone_number text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('rider','captain','admin')),
  verified_at timestamptz,
  password_changed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.vehicle_types (
  id text PRIMARY KEY CHECK (lower(id) <> 'elite'),
  name_ar text NOT NULL CHECK (lower(name_ar) NOT LIKE '%elite%'),
  capacity_max integer NOT NULL CHECK (capacity_max > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.service_categories (
  id text PRIMARY KEY CHECK (lower(id) <> 'elite'),
  vehicle_type_id text NOT NULL REFERENCES public.vehicle_types(id),
  name_ar text NOT NULL CHECK (lower(name_ar) NOT LIKE '%elite%'),
  max_seats integer NOT NULL CHECK (max_seats > 0),
  ac_rule text NOT NULL CHECK (ac_rule IN ('none','required','optional')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz
);
CREATE INDEX idx_sessions_user_id ON public.sessions(user_id);
CREATE INDEX idx_sessions_token_hash ON public.sessions(token_hash);
CREATE TABLE public.captain_profiles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES public.users(id),
  vehicle_type_id text NOT NULL REFERENCES public.vehicle_types(id),
  license_number text NOT NULL,
  vehicle_plate text NOT NULL,
  verification_status text NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending','approved','rejected')),
  current_lat double precision CHECK (current_lat IS NULL OR current_lat BETWEEN -90 AND 90),
  current_lng double precision CHECK (current_lng IS NULL OR current_lng BETWEEN -180 AND 180),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_captain_profiles_user_id ON public.captain_profiles(user_id);
CREATE TABLE public.otp_challenges (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  otp_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  purpose text NOT NULL CHECK (purpose = 'phone_verification')
);
CREATE INDEX idx_otp_challenges_user_id ON public.otp_challenges(user_id);
CREATE TABLE public.daily_commute_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_user_id integer NOT NULL REFERENCES public.users(id),
  service_category_id text NOT NULL REFERENCES public.service_categories(id),
  pickup_lat double precision NOT NULL CHECK (pickup_lat BETWEEN -90 AND 90),
  pickup_lng double precision NOT NULL CHECK (pickup_lng BETWEEN -180 AND 180),
  dropoff_lat double precision NOT NULL CHECK (dropoff_lat BETWEEN -90 AND 90),
  dropoff_lng double precision NOT NULL CHECK (dropoff_lng BETWEEN -180 AND 180),
  requested_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','matched','cancelled','expired')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_daily_commute_requests_rider_user_id ON public.daily_commute_requests(rider_user_id);
CREATE INDEX idx_daily_commute_requests_status ON public.daily_commute_requests(status);
CREATE TABLE public.matches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_commute_request_id integer NOT NULL UNIQUE REFERENCES public.daily_commute_requests(id),
  captain_user_id integer NOT NULL REFERENCES public.users(id),
  distance_km double precision NOT NULL CHECK (distance_km >= 0),
  matched_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_matches_captain_user_id ON public.matches(captain_user_id);
CREATE TABLE public.trips (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id integer NOT NULL UNIQUE REFERENCES public.matches(id),
  status text NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress','completed')),
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  total_distance_km double precision CHECK (total_distance_km IS NULL OR total_distance_km >= 0),
  total_amount double precision CHECK (total_amount IS NULL OR total_amount >= 0)
);
CREATE TABLE public.trip_stops (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id integer NOT NULL REFERENCES public.trips(id),
  sequence integer NOT NULL CHECK (sequence IN (1,2)),
  lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
  reached_at timestamptz,
  fare_at_stop double precision CHECK (fare_at_stop IS NULL OR fare_at_stop >= 0),
  UNIQUE(trip_id,sequence)
);
CREATE INDEX idx_trip_stops_trip_id ON public.trip_stops(trip_id);
CREATE TABLE public.pricing_config (
  vehicle_type_id text PRIMARY KEY REFERENCES public.vehicle_types(id),
  base_fee double precision NOT NULL CHECK (base_fee >= 0),
  rate_per_km double precision NOT NULL CHECK (rate_per_km >= 0),
  rate_per_min double precision NOT NULL CHECK (rate_per_min >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id integer NOT NULL UNIQUE REFERENCES public.trips(id),
  amount double precision NOT NULL CHECK (amount >= 0),
  reported_by_user_id integer NOT NULL REFERENCES public.users(id),
  reported_at timestamptz NOT NULL DEFAULT now(),
  confirmed_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.payment_status_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id integer NOT NULL REFERENCES public.payments(id),
  from_status text NOT NULL CHECK (from_status IN ('confirmed','disputed','resolved','adjusted','voided')),
  to_status text NOT NULL CHECK (to_status IN ('confirmed','disputed','resolved','adjusted','voided')),
  actor_user_id integer REFERENCES public.users(id),
  reason text,
  adjusted_amount double precision CHECK (adjusted_amount IS NULL OR adjusted_amount >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_payment_status_events_payment_id ON public.payment_status_events(payment_id);
CREATE TABLE public.pool_categories (
  id text PRIMARY KEY,
  speed_tier text NOT NULL CHECK (speed_tier IN ('faster','saver')),
  has_ac smallint NOT NULL CHECK (has_ac IN (0,1)),
  seats integer NOT NULL CHECK (seats >= 1),
  base_fee double precision NOT NULL CHECK (base_fee >= 0),
  rate_per_km double precision NOT NULL CHECK (rate_per_km >= 0),
  rate_per_min double precision NOT NULL CHECK (rate_per_min >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.pool_groups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by_user_id integer NOT NULL REFERENCES public.users(id),
  category_id text NOT NULL REFERENCES public.pool_categories(id),
  package_type text NOT NULL CHECK (package_type IN ('daily','weekly','monthly')),
  service_dates jsonb NOT NULL CHECK (jsonb_typeof(service_dates)='array'),
  morning_departure time NOT NULL,
  return_departure time NOT NULL,
  status text NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting','minimum_met','active','price_review','needs_captain','cancelled','completed')),
  route_distance_km double precision CHECK (route_distance_km IS NULL OR route_distance_km >= 0),
  route_duration_min double precision CHECK (route_duration_min IS NULL OR route_duration_min >= 0),
  seat_day_fare double precision CHECK (seat_day_fare IS NULL OR seat_day_fare >= 0),
  route_geometry jsonb,
  route_version integer NOT NULL DEFAULT 0,
  fixed_captain_user_id integer REFERENCES public.users(id),
  waiting_since timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.pool_members (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL REFERENCES public.pool_groups(id),
  rider_user_id integer NOT NULL REFERENCES public.users(id),
  pickup_lat double precision NOT NULL CHECK (pickup_lat BETWEEN -90 AND 90),
  pickup_lng double precision NOT NULL CHECK (pickup_lng BETWEEN -180 AND 180),
  dropoff_lat double precision NOT NULL CHECK (dropoff_lat BETWEEN -90 AND 90),
  dropoff_lng double precision NOT NULL CHECK (dropoff_lng BETWEEN -180 AND 180),
  seats_reserved integer NOT NULL DEFAULT 1 CHECK (seats_reserved >= 1),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('awaiting_confirmation','active','cancelled')),
  price_decision text NOT NULL DEFAULT 'pending' CHECK (price_decision IN ('pending','accepted')),
  pickup_order integer NOT NULL DEFAULT 0 CHECK (pickup_order >= 0),
  joined_at timestamptz NOT NULL DEFAULT now(),
  cancelled_at timestamptz,
  UNIQUE(group_id,rider_user_id)
);
CREATE INDEX idx_pool_members_group_status ON public.pool_members(group_id,status);
CREATE INDEX idx_pool_members_rider ON public.pool_members(rider_user_id,status);
CREATE TABLE public.pool_subscriptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL REFERENCES public.pool_groups(id),
  member_id integer NOT NULL UNIQUE REFERENCES public.pool_members(id),
  package_type text NOT NULL CHECK (package_type IN ('daily','weekly','monthly')),
  seat_day_fare double precision NOT NULL CHECK (seat_day_fare >= 0),
  discount_rate double precision NOT NULL CHECK (discount_rate BETWEEN 0 AND 0.10),
  service_days integer NOT NULL CHECK (service_days >= 1),
  seats_reserved integer NOT NULL CHECK (seats_reserved >= 1),
  amount_due double precision NOT NULL CHECK (amount_due >= 0),
  cancelled_at timestamptz,
  refund_amount double precision NOT NULL DEFAULT 0 CHECK (refund_amount >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.pool_trips (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL REFERENCES public.pool_groups(id),
  service_date date NOT NULL,
  direction text NOT NULL CHECK (direction IN ('outbound','return')),
  departure_at timestamptz NOT NULL,
  estimated_arrival_at timestamptz,
  captain_user_id integer REFERENCES public.users(id),
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','assigned','in_progress','completed','cancelled','needs_captain')),
  started_at timestamptz,
  completed_at timestamptz,
  UNIQUE(group_id,service_date,direction)
);
CREATE INDEX idx_pool_trips_captain_time ON public.pool_trips(captain_user_id,departure_at,status);
CREATE INDEX idx_pool_trips_status_time ON public.pool_trips(status,departure_at);
CREATE TABLE public.pool_trip_stops (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id integer NOT NULL REFERENCES public.pool_trips(id),
  member_id integer NOT NULL REFERENCES public.pool_members(id),
  stop_type text NOT NULL CHECK (stop_type IN ('pickup','dropoff')),
  sequence integer NOT NULL CHECK (sequence >= 1),
  lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
  reached_at timestamptz,
  UNIQUE(trip_id,sequence),
  UNIQUE(trip_id,member_id,stop_type)
);
CREATE TABLE public.pool_ledger (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id integer NOT NULL REFERENCES public.pool_trips(id),
  member_id integer NOT NULL REFERENCES public.pool_members(id),
  list_amount double precision NOT NULL CHECK (list_amount >= 0),
  rider_amount double precision NOT NULL CHECK (rider_amount >= 0),
  discount_amount double precision NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  company_share_amount double precision NOT NULL DEFAULT 0 CHECK (company_share_amount >= 0),
  captain_share_amount double precision NOT NULL DEFAULT 0 CHECK (captain_share_amount >= 0),
  company_commission_rate double precision NOT NULL DEFAULT 0.20 CHECK (company_commission_rate BETWEEN 0 AND 1),
  settlement_status text NOT NULL DEFAULT 'pending' CHECK (settlement_status IN ('pending','settled','voided')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(trip_id,member_id)
);
CREATE TABLE public.pool_trip_cancellations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id integer NOT NULL REFERENCES public.pool_trips(id),
  member_id integer NOT NULL REFERENCES public.pool_members(id),
  charge_amount double precision NOT NULL CHECK (charge_amount >= 0),
  refund_amount double precision NOT NULL CHECK (refund_amount >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(trip_id,member_id)
);
CREATE TABLE public.pool_captain_stats (
  captain_user_id integer PRIMARY KEY REFERENCES public.users(id),
  absences integer NOT NULL DEFAULT 0 CHECK (absences >= 0),
  search_radius_km double precision NOT NULL DEFAULT 4 CHECK (search_radius_km BETWEEN 4 AND 10)
);
CREATE TABLE public.pool_captain_capabilities (
  captain_user_id integer PRIMARY KEY REFERENCES public.users(id),
  has_ac smallint NOT NULL CHECK (has_ac IN (0,1)),
  accepts_faster smallint NOT NULL DEFAULT 1 CHECK (accepts_faster IN (0,1)),
  accepts_saver smallint NOT NULL DEFAULT 1 CHECK (accepts_saver IN (0,1)),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (accepts_faster=1 OR accepts_saver=1)
);
CREATE TABLE public.pool_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id),
  group_id integer REFERENCES public.pool_groups(id),
  event_key text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz,
  UNIQUE(user_id,event_key)
);
CREATE INDEX idx_pool_notifications_user ON public.pool_notifications(user_id,read_at,id);
CREATE TABLE public.pool_captain_escrows (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL UNIQUE REFERENCES public.pool_groups(id),
  original_captain_user_id integer NOT NULL REFERENCES public.users(id),
  package_type text NOT NULL CHECK (package_type IN ('weekly','monthly')),
  service_days integer NOT NULL CHECK (service_days BETWEEN 1 AND 22),
  daily_captain_share_amount double precision NOT NULL CHECK (daily_captain_share_amount >= 0),
  reserved_amount double precision NOT NULL CHECK (reserved_amount >= 0),
  used_amount double precision NOT NULL DEFAULT 0 CHECK (used_amount >= 0 AND used_amount <= reserved_amount),
  released_amount double precision NOT NULL DEFAULT 0 CHECK (released_amount >= 0),
  status text NOT NULL DEFAULT 'reserved' CHECK (status IN ('reserved','released')),
  created_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz
);
CREATE TABLE public.pool_captain_escrow_transfers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escrow_id integer NOT NULL REFERENCES public.pool_captain_escrows(id),
  trip_id integer NOT NULL UNIQUE REFERENCES public.pool_trips(id),
  original_captain_user_id integer NOT NULL REFERENCES public.users(id),
  replacement_captain_user_id integer NOT NULL REFERENCES public.users(id),
  amount_due double precision NOT NULL CHECK (amount_due >= 0),
  escrow_funded_amount double precision NOT NULL CHECK (escrow_funded_amount >= 0 AND escrow_funded_amount <= amount_due),
  unfunded_amount double precision NOT NULL CHECK (unfunded_amount >= 0),
  transfer_status text NOT NULL DEFAULT 'pending' CHECK (transfer_status IN ('pending','transferred')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (abs(amount_due - escrow_funded_amount - unfunded_amount) < 0.01)
);
CREATE INDEX idx_pool_escrows_status ON public.pool_captain_escrows(status,group_id);
CREATE INDEX idx_pool_escrow_transfers_replacement ON public.pool_captain_escrow_transfers(replacement_captain_user_id,transfer_status);
CREATE TABLE public.push_subscriptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE CHECK (length(endpoint) BETWEEN 12 AND 4096),
  p256dh text NOT NULL CHECK (length(p256dh) BETWEEN 16 AND 256),
  auth text NOT NULL CHECK (length(auth) BETWEEN 8 AND 128),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_push_subscriptions_user ON public.push_subscriptions(user_id,id);

-- Seed only backend-controlled catalog/pricing data; deliberately do not seed
-- the old predictable admin password from SQLite migration 007.
INSERT INTO public.vehicle_types(id,name_ar,capacity_max) VALUES
 ('private_car','ملاكي',3),('hiace','هاي إس',14);
INSERT INTO public.service_categories(id,vehicle_type_id,name_ar,max_seats,ac_rule) VALUES
 ('faster','private_car','فاستر',3,'none'),
 ('plus','private_car','بلس',3,'required'),
 ('saver','hiace','سيفر',14,'optional');
INSERT INTO public.pricing_config(vehicle_type_id,base_fee,rate_per_km,rate_per_min) VALUES
 ('private_car',10,3.5,0.5),('hiace',15,5,0.75);
INSERT INTO public.pool_categories(id,speed_tier,has_ac,seats,base_fee,rate_per_km,rate_per_min) VALUES
 ('faster_non_ac','faster',0,3,10,7.3,0.50),
 ('faster_ac','faster',1,3,12,8.2,0.60),
 ('saver_non_ac','saver',0,4,15,7.3,0.75),
 ('saver_ac','saver',1,4,17,8.2,0.85);

-- Database-level role/domain guards.
CREATE OR REPLACE FUNCTION public.sekka_require_role() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE
  referenced_user integer;
BEGIN
  referenced_user := (to_jsonb(NEW)->>TG_ARGV[0])::integer;
  IF referenced_user IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.users u WHERE u.id=referenced_user AND u.role=ANY(string_to_array(TG_ARGV[1],','))
  ) THEN
    RAISE EXCEPTION '% must reference a user with role %', TG_TABLE_NAME, TG_ARGV[1]
      USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_captain_profiles_role BEFORE INSERT OR UPDATE OF user_id ON public.captain_profiles
FOR EACH ROW EXECUTE FUNCTION public.sekka_require_role('user_id','captain');
CREATE TRIGGER trg_daily_requests_role BEFORE INSERT OR UPDATE OF rider_user_id ON public.daily_commute_requests
FOR EACH ROW EXECUTE FUNCTION public.sekka_require_role('rider_user_id','rider');
CREATE TRIGGER trg_matches_captain_role BEFORE INSERT OR UPDATE OF captain_user_id ON public.matches
FOR EACH ROW EXECUTE FUNCTION public.sekka_require_role('captain_user_id','captain');
CREATE TRIGGER trg_pool_group_creator_role BEFORE INSERT OR UPDATE OF created_by_user_id ON public.pool_groups
FOR EACH ROW EXECUTE FUNCTION public.sekka_require_role('created_by_user_id','rider,captain');
CREATE TRIGGER trg_pool_member_rider_role BEFORE INSERT OR UPDATE OF rider_user_id ON public.pool_members
FOR EACH ROW EXECUTE FUNCTION public.sekka_require_role('rider_user_id','rider');
CREATE TRIGGER trg_pool_trip_captain_role BEFORE INSERT OR UPDATE OF captain_user_id ON public.pool_trips
FOR EACH ROW WHEN (NEW.captain_user_id IS NOT NULL)
EXECUTE FUNCTION public.sekka_require_role('captain_user_id','captain');

CREATE OR REPLACE FUNCTION public.sekka_validate_vehicle_capacity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE
  current_capacity integer;
BEGIN
  IF TG_TABLE_NAME='service_categories' THEN
    SELECT capacity_max INTO current_capacity FROM public.vehicle_types WHERE id=NEW.vehicle_type_id;
    IF NEW.max_seats > current_capacity THEN
      RAISE EXCEPTION 'service category max_seats exceeds vehicle capacity' USING ERRCODE='23514';
    END IF;
  ELSE
    IF EXISTS (SELECT 1 FROM public.service_categories c WHERE c.vehicle_type_id=NEW.id AND c.max_seats>NEW.capacity_max) THEN
      RAISE EXCEPTION 'vehicle capacity would violate service category capacity' USING ERRCODE='23514';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_service_category_capacity BEFORE INSERT OR UPDATE ON public.service_categories
FOR EACH ROW EXECUTE FUNCTION public.sekka_validate_vehicle_capacity();
CREATE TRIGGER trg_vehicle_capacity_update BEFORE UPDATE OF capacity_max ON public.vehicle_types
FOR EACH ROW EXECUTE FUNCTION public.sekka_validate_vehicle_capacity();

CREATE OR REPLACE FUNCTION public.sekka_match_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $fn$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.users u WHERE u.id=NEW.captain_user_id AND u.role='captain') THEN
    RAISE EXCEPTION 'match captain must have captain role' USING ERRCODE='23514';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.daily_commute_requests r WHERE r.id=NEW.daily_commute_request_id AND r.status='open') THEN
    RAISE EXCEPTION 'only open requests can be matched' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $fn$;
CREATE TRIGGER trg_match_guard BEFORE INSERT ON public.matches
FOR EACH ROW EXECUTE FUNCTION public.sekka_match_guard();

CREATE OR REPLACE FUNCTION public.sekka_match_creates_trip() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE new_trip_id integer;
BEGIN
  INSERT INTO public.trips(match_id) VALUES(NEW.id) RETURNING id INTO new_trip_id;
  INSERT INTO public.trip_stops(trip_id,sequence,lat,lng)
  SELECT new_trip_id,1,pickup_lat,pickup_lng FROM public.daily_commute_requests WHERE id=NEW.daily_commute_request_id;
  INSERT INTO public.trip_stops(trip_id,sequence,lat,lng)
  SELECT new_trip_id,2,dropoff_lat,dropoff_lng FROM public.daily_commute_requests WHERE id=NEW.daily_commute_request_id;
  UPDATE public.daily_commute_requests SET status='matched' WHERE id=NEW.daily_commute_request_id;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_matches_create_trip AFTER INSERT ON public.matches
FOR EACH ROW EXECUTE FUNCTION public.sekka_match_creates_trip();
CREATE OR REPLACE FUNCTION public.sekka_trip_stop_order() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
  IF NEW.reached_at IS NOT NULL AND NEW.sequence>1 AND EXISTS (
    SELECT 1 FROM public.trip_stops s WHERE s.trip_id=NEW.trip_id AND s.sequence=NEW.sequence-1 AND s.reached_at IS NULL
  ) THEN
    RAISE EXCEPTION 'trip stops must be reached in sequence order' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_trip_stop_order BEFORE UPDATE OF reached_at ON public.trip_stops
FOR EACH ROW EXECUTE FUNCTION public.sekka_trip_stop_order();
CREATE OR REPLACE FUNCTION public.sekka_trip_complete_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
  IF NEW.status='completed' AND OLD.status<>'completed' AND EXISTS (
    SELECT 1 FROM public.trip_stops s WHERE s.trip_id=NEW.id AND s.reached_at IS NULL
  ) THEN
    RAISE EXCEPTION 'all trip stops must be reached before completion' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_trip_complete_guard BEFORE UPDATE OF status ON public.trips
FOR EACH ROW EXECUTE FUNCTION public.sekka_trip_complete_guard();

CREATE OR REPLACE FUNCTION public.sekka_append_only() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN RAISE EXCEPTION '% rows are append-only', TG_TABLE_NAME USING ERRCODE='55000'; END $$;
CREATE TRIGGER trg_payments_no_update BEFORE UPDATE OR DELETE ON public.payments
FOR EACH ROW EXECUTE FUNCTION public.sekka_append_only();
CREATE TRIGGER trg_payment_events_no_update BEFORE UPDATE OR DELETE ON public.payment_status_events
FOR EACH ROW EXECUTE FUNCTION public.sekka_append_only();
CREATE TRIGGER trg_pool_ledger_no_update BEFORE UPDATE OR DELETE ON public.pool_ledger
FOR EACH ROW EXECUTE FUNCTION public.sekka_append_only();
CREATE TRIGGER trg_escrow_transfers_no_update BEFORE UPDATE OR DELETE ON public.pool_captain_escrow_transfers
FOR EACH ROW EXECUTE FUNCTION public.sekka_append_only();
CREATE OR REPLACE FUNCTION public.sekka_payment_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE trip_status text; reporter integer; actor_role text;
BEGIN
  IF TG_TABLE_NAME='payments' THEN
    SELECT status INTO trip_status FROM public.trips WHERE id=NEW.trip_id;
    IF trip_status IS DISTINCT FROM 'completed' THEN
      RAISE EXCEPTION 'payments require a completed trip' USING ERRCODE='23514';
    END IF;
  ELSE
    IF NEW.to_status IN ('resolved','adjusted','voided') THEN
      IF NEW.from_status<>'disputed' THEN RAISE EXCEPTION 'admin transitions require disputed status' USING ERRCODE='23514'; END IF;
      SELECT role INTO actor_role FROM public.users WHERE id=NEW.actor_user_id;
      IF actor_role IS DISTINCT FROM 'admin' THEN RAISE EXCEPTION 'admin actor required' USING ERRCODE='23514'; END IF;
    END IF;
    IF NEW.to_status='adjusted' AND NEW.adjusted_amount IS NULL THEN
      RAISE EXCEPTION 'adjusted amount is required' USING ERRCODE='23514';
    END IF;
    IF NEW.to_status='confirmed' AND NEW.actor_user_id IS NOT NULL THEN
      SELECT reported_by_user_id INTO reporter FROM public.payments WHERE id=NEW.payment_id;
      IF reporter=NEW.actor_user_id THEN RAISE EXCEPTION 'reporter cannot confirm own payment' USING ERRCODE='23514'; END IF;
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_payment_trip_guard BEFORE INSERT ON public.payments
FOR EACH ROW EXECUTE FUNCTION public.sekka_payment_guard();
CREATE TRIGGER trg_payment_event_guard BEFORE INSERT ON public.payment_status_events
FOR EACH ROW EXECUTE FUNCTION public.sekka_payment_guard();
CREATE OR REPLACE FUNCTION public.sekka_captain_verification_noop() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
  IF NEW.verification_status=OLD.verification_status THEN
    RAISE EXCEPTION 'verification status must change' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_captain_verification_noop BEFORE UPDATE OF verification_status ON public.captain_profiles
FOR EACH ROW EXECUTE FUNCTION public.sekka_captain_verification_noop();

-- Defense in depth: all tables are inaccessible to anon/authenticated SQL API.
-- Edge Functions use a server-side service key and enforce user/role checks.
DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='public' LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t.tablename);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated',t.tablename);
    EXECUTE format('GRANT ALL ON TABLE public.%I TO service_role',t.tablename);
  END LOOP;
END $$;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
