import { useEffect, useMemo, useState } from "react";
import { api } from "../api";
import { errorText } from "../lib/formatters";
import type { Session, Toast } from "../types";

type Tab = "users" | "verification" | "trips" | "disputes" | "finance" | "settings" | "audit";
type Row = Record<string, any>;
const tabGroups: Array<{ label: string; tabs: Array<[Tab, string]> }> = [
  { label: "الحسابات والتوثيق", tabs: [["users", "المستخدمون"], ["verification", "توثيق المستندات"]] },
  { label: "الرحلات وخدمة العملاء", tabs: [["trips", "الرحلات"], ["disputes", "الاعتراضات"]] },
  { label: "المالية والتسعير", tabs: [["finance", "المالية"], ["settings", "التسعير"]] },
  { label: "المراجعة", tabs: [["audit", "سجل التدقيق"]] },
];
const field = "w-full rounded-xl border border-stone-700 bg-[#121212] px-3 py-2 text-white outline-none focus:border-[#EAB308]";

export default function AdminControlPanel({ session, notify }: { session: Session; notify: (text: string, tone?: Toast["tone"]) => void }) {
  const [tab, setTab] = useState<Tab>("users");
  const [users, setUsers] = useState<Row[]>([]), [trips, setTrips] = useState<{ daily_trips: Row[]; pool_trips: Row[] }>({ daily_trips: [], pool_trips: [] });
  const [disputes, setDisputes] = useState<Row[]>([]), [settings, setSettings] = useState<Row | null>(null), [audit, setAudit] = useState<Row[]>([]);
  const [ledgerRows, setLedgerRows] = useState<Row[]>([]);
  const [verificationDocuments, setVerificationDocuments] = useState<Row[]>([]);
  const [query, setQuery] = useState(""), [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(false), [loadError, setLoadError] = useState("");
  const auth = { token: session.token };
  async function load(target: Tab = tab) {
    setLoading(true); setLoadError("");
    try {
      if (target === "users") setUsers((await api<{users:Row[]}>("/admin/users?q=" + encodeURIComponent(query), auth)).users);
      if (target === "trips") setTrips(await api<{ daily_trips: Row[]; pool_trips: Row[] }>("/admin/trips", auth));
      if (target === "disputes") setDisputes((await api<{disputes:Row[]}>("/admin/disputes", auth)).disputes);
      if (target === "verification") setVerificationDocuments((await api<{documents:Row[]}>("/admin/verifications?status=all", auth)).documents);
      if (target === "settings" || target === "finance") {
        const [config, ledger] = await Promise.all([api<Row>("/admin/settings", auth), api<{ adjustments: Row[] }>("/admin/ledger/adjustments?limit=100", auth)]);
        setSettings(config); setLedgerRows(ledger.adjustments);
      }
      if (target === "audit") setAudit((await api<{audit_logs:Row[]}>("/admin/audit?limit=100", auth)).audit_logs);
    } catch (error) {
      setLoadError(errorText(error));
      throw error;
    } finally {
      setLoading(false);
    }
  }
  useEffect(() => { void load().catch((e) => notify(errorText(e), "error")); }, [tab]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (tab !== "users") return; const timer = window.setTimeout(() => void load("users").catch((e) => notify(errorText(e), "error")), 250); return () => window.clearTimeout(timer); }, [query, tab]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => {
    if (tab !== "verification") return;
    const timer = window.setInterval(() => { void load("verification").catch(() => undefined); }, 20_000);
    return () => window.clearInterval(timer);
  }, [tab]); // eslint-disable-line react-hooks/exhaustive-deps
  async function perform(path: string, method: string, body: unknown, success: string, refresh = tab) {
    setBusy(true); try { await api(path, { ...auth, method, body }); notify(success, "success"); await load(refresh); }
    catch (e) { notify(errorText(e), "error"); } finally { setBusy(false); }
  }
  const allTrips = useMemo<Array<Row & { kind: string }>>(() => [...trips.daily_trips.map((x) => ({...x, kind:"daily"})), ...trips.pool_trips.map((x) => ({...x, kind:"pool"}))], [trips]);
  return <section dir="rtl" className="admin-control-panel mx-auto w-full max-w-7xl space-y-5 px-4 py-5 text-right text-[#f5f0e3] sm:px-6" aria-busy={loading}>
    <header className="admin-panel-heading"><div><p className="text-sm font-bold text-[#EAB308]">SeKKa · تحكم آمن</p><h2 className="mt-1 text-2xl font-extrabold">مركز إدارة المنصة</h2><p className="mt-1 text-sm text-stone-400">كل تغيير حساس يُسجل مع سببه في سجل التدقيق.</p></div><button type="button" className="button button-outline button-small" onClick={() => void load().catch((e) => notify(errorText(e), "error"))}>تحديث البيانات</button></header>
    <aside className="admin-permissions-note"><span aria-hidden="true">▣</span><div><strong>صلاحيات إدارة محمية</strong><p>تظهر هذه الأدوات لحسابات الإدارة المخوّلة فقط، وتُراجع تغييراتها من سجل التدقيق.</p></div></aside>
    <nav aria-label="أقسام الإدارة" className="admin-nav-groups">{tabGroups.map((group) => <section className="admin-nav-group" key={group.label} aria-label={group.label}><h3>{group.label}</h3><div>{group.tabs.map(([id,label]) => <button key={id} type="button" aria-current={id === tab ? "page" : undefined} onClick={() => setTab(id)}>{label}</button>)}</div></section>)}</nav>
    {loadError && <div className="admin-load-feedback" role="alert"><span>{loadError}</span><button type="button" onClick={() => void load().catch((error) => notify(errorText(error), "error"))}>إعادة المحاولة</button></div>}
    {loading && <p className="admin-load-status" role="status"><span className="spinner" /> جارٍ تحميل بيانات هذا القسم…</p>}
    {tab === "users" && <div className="space-y-3"><input className={field} placeholder="ابحث بالاسم أو الهاتف" value={query} onChange={(e) => setQuery(e.target.value)} />{users.map((u) => <article key={u.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-stone-800 bg-[#181818] p-4"><div><strong className="text-lg">{u.full_name}</strong><p className="text-sm text-stone-400">{u.phone_number} · {u.role} · <AdminStatus status={String(u.account_status)} /></p>{u.captain && <p className="text-xs text-stone-500">مركبة {u.captain.vehicle_type_id} · لوحة {u.captain.vehicle_plate} · رخصة {u.captain.license_number} · التوثيق {u.captain.verification_status}</p>}</div><div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded-lg border border-stone-700 px-3 py-2 text-xs hover:border-[#EAB308]" onClick={() => { const full_name=window.prompt("اسم المستخدم",u.full_name); const phone_number=full_name && window.prompt("رقم الهاتف",u.phone_number); const reason=phone_number && window.prompt("سبب تعديل الحساب"); if(full_name?.trim()&&phone_number?.trim()&&reason?.trim()) void perform("/admin/users/"+u.id,"PATCH",{full_name:full_name.trim(),phone_number:phone_number.trim(),reason:reason.trim()},"تم تحديث الحساب.","users"); }}>تعديل الحساب</button>{u.captain && <button disabled={busy} className="rounded-lg border border-stone-700 px-3 py-2 text-xs hover:border-[#EAB308]" onClick={() => { const vehicle_type_id=window.prompt("نوع المركبة",u.captain.vehicle_type_id); const license_number=vehicle_type_id && window.prompt("رقم الرخصة",u.captain.license_number); const vehicle_plate=license_number && window.prompt("رقم اللوحة",u.captain.vehicle_plate); const reason=vehicle_plate && window.prompt("سبب تعديل بيانات المركبة"); if(vehicle_type_id?.trim()&&license_number?.trim()&&vehicle_plate?.trim()&&reason?.trim()) void perform("/admin/captains/"+u.id,"PATCH",{vehicle_type_id:vehicle_type_id.trim(),license_number:license_number.trim(),vehicle_plate:vehicle_plate.trim(),reason:reason.trim()},"تم تحديث بيانات الكابتن.","users"); }}>تعديل المركبة</button>}{(["active","suspended","banned"] as const).filter((s) => s !== u.account_status).map((status) => <button key={status} disabled={busy} className="rounded-lg border border-stone-700 px-3 py-2 text-xs hover:border-[#EAB308]" onClick={() => { const reason = window.prompt("سبب تغيير حالة الحساب"); if (reason?.trim()) void perform("/admin/users/" + u.id + "/status","PATCH",{status,reason},"تم تحديث حالة الحساب.","users"); }}>{status === "active" ? "إعادة التفعيل" : status === "suspended" ? "إيقاف مؤقت" : "حظر"}</button>)}</div></article>)}</div>}
    {tab === "verification" && <VerificationQueue documents={verificationDocuments} loading={loading} loadError={loadError} session={session} notify={notify} refresh={() => load("verification")} />}
    {tab === "trips" && <div className="space-y-3">{allTrips.map((t) => <article key={t.kind + t.id} className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4"><div className="flex justify-between"><strong>رحلة {t.kind === "pool" ? "مجموعة" : "يومية"} #{t.id}</strong><AdminStatus status={String(t.status)} /></div><p className="text-sm text-stone-400">{t.departure_at || t.started_at || t.service_date} · الكابتن {t.captain_user_id || "غير معين"}</p><div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded-lg border border-red-900 px-3 py-2 text-sm text-red-300 disabled:opacity-50" onClick={() => { const reason=window.prompt("سبب الإلغاء"); const reason_tag=reason && window.prompt("تصنيف السبب (other / route_issue / safety / captain_unavailable)","other"); if(reason?.trim() && reason_tag?.trim()) void perform("/admin/trips/"+t.kind+"/"+t.id+"/cancel","POST",{reason,reason_tag},"تم إلغاء الرحلة.","trips"); }}>إلغاء الرحلة</button><button disabled={busy} className="rounded-lg border border-stone-700 px-3 py-2 text-sm hover:border-[#EAB308] disabled:opacity-50" onClick={() => { const captain_user_id=Number(window.prompt("رقم حساب الكابتن الموثق")); const reason=window.prompt("سبب إعادة التعيين"); if(Number.isInteger(captain_user_id)&&captain_user_id>0&&reason?.trim()) void perform("/admin/trips/"+t.kind+"/"+t.id+"/captain","POST",{captain_user_id,reason},"تم تعيين الكابتن.","trips"); }}>إعادة تعيين الكابتن</button></div></article>)}{!allTrips.length && !loading && !loadError && <Empty text="لا توجد رحلات قابلة للإجراء حاليًا."/>}</div>}
    {tab === "disputes" && <div className="space-y-3">{disputes.map((d) => <Dispute key={d.payment_id} row={d} session={session} notify={notify} refresh={() => load("disputes")}/>)}{!disputes.length && !loading && !loadError && <Empty text="لا توجد اعتراضات مفتوحة."/>}</div>}
    {(tab === "finance" || tab === "settings") && settings && <div className="grid gap-4 lg:grid-cols-2"><Commission token={session.token} initial={Number(settings.commission_rate)} notify={notify} reload={() => load("settings")}/><Ledger session={session} notify={notify} reload={() => load("finance")}/><div className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4"><h3 className="text-lg font-bold">تسويات دفترية حديثة</h3>{ledgerRows.map((x)=><div key={x.id} className="flex flex-wrap justify-between gap-2 border-t border-stone-800 py-2 text-sm"><span>رحلة {x.trip_kind} #{x.trip_id} · {x.reason}</span><strong className={Number(x.amount)<0?"text-red-300":"text-[#EAB308]"}>{Number(x.amount).toLocaleString("ar-EG")} ج.م</strong></div>)}{!ledgerRows.length&&<p className="text-sm text-stone-500">لا توجد تسويات يدوية.</p>}</div><div className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4 lg:col-span-2"><h3 className="text-lg font-bold">تسعير الرحلات اليومية</h3>{settings.pricing?.map((x:Row)=><Pricing key={x.vehicle_type_id} row={x} token={session.token} notify={notify} reload={()=>load("settings")}/>)}</div><div className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4 lg:col-span-2"><h3 className="text-lg font-bold">تسعير فئات المجموعات</h3>{settings.pool_categories?.map((x:Row)=><Pricing key={x.id} row={{...x,vehicle_type_id:x.id,label:x.speed_tier+" · "+(x.has_ac?"مكيف":"بدون تكييف")}} pool token={session.token} notify={notify} reload={()=>load("settings")}/>)}</div></div>}
    {tab === "audit" && <div className="overflow-x-auto rounded-2xl border border-stone-800"><table className="w-full min-w-[680px] text-sm"><thead className="bg-[#1c1c1c]"><tr>{["الوقت","المسؤول","الإجراء","العنصر","السبب"].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{audit.map((x)=><tr key={x.id} className="border-t border-stone-800"><td className="p-3 text-stone-400">{new Date(x.created_at).toLocaleString("ar-EG")}</td><td className="p-3">#{x.actor_user_id}</td><td className="p-3 text-[#EAB308]">{x.action}</td><td className="p-3">{x.resource_type} · {x.resource_id}</td><td className="max-w-xs truncate p-3 text-stone-400">{x.reason || "—"}</td></tr>)}</tbody></table>{!audit.length && !loading && !loadError && <Empty text="سجل التدقيق فارغ."/>}</div>}
  </section>;
}
function Dispute({row,session,notify,refresh}:{row:Row;session:Session;notify:(text:string,tone?:"success"|"error"|"info")=>void;refresh:()=>Promise<void>}) {
 const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false);
 return <article className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4"><div className="flex justify-between"><strong>اعتراض الدفعة #{row.payment_id}</strong><span className="text-[#EAB308]">{row.payment?.amount} ج.م</span></div><p className="text-sm text-stone-400">رحلة #{row.payment?.trip_id} · مقدم الاعتراض #{row.payment?.reported_by_user_id}</p><textarea className={field} rows={2} placeholder="سبب القرار الإداري" value={reason} onChange={(e)=>setReason(e.target.value)}/><div className="flex flex-wrap gap-2">{(["resolve","adjust","void"] as const).map((action)=><button key={action} disabled={busy||reason.trim().length<3} className="rounded-lg border border-stone-700 px-3 py-2 text-sm hover:border-[#EAB308] disabled:opacity-40" onClick={async()=>{const adjusted_amount=action==="adjust"?Number(window.prompt("المبلغ المعدل بالجنيه")):undefined;if(action==="adjust"&&!Number.isFinite(adjusted_amount))return;setBusy(true);try{await api("/admin/payments/"+row.payment_id+"/"+action,{token:session.token,method:"POST",body:{reason,...(adjusted_amount===undefined?{}:{adjusted_amount})}});notify("تم حفظ قرار الاعتراض.","success");await refresh()}catch(e){notify(errorText(e),"error")}finally{setBusy(false)}}}>{action==="resolve"?"حسم الاعتراض":action==="adjust"?"تعديل المبلغ":"إلغاء الدفعة"}</button>)}</div></article>;
}
function Commission({token,initial,notify,reload}:{token:string;initial:number;notify:(text:string,tone?:"success"|"error"|"info")=>void;reload:()=>Promise<void>}) {
 const [rate,setRate]=useState(String(initial));
 useEffect(()=>setRate(String(initial)),[initial]);
 return <article className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4"><h3 className="text-lg font-bold">عمولة المنصة</h3><input className={field} type="number" min="0" max="1" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/><button className="admin-primary rounded-lg bg-[#EAB308] px-4 py-2 font-bold text-black" onClick={async()=>{const reason=window.prompt("سبب تغيير العمولة");if(!reason?.trim())return;try{await api("/admin/settings/commission",{token,method:"PATCH",body:{rate:Number(rate),reason}});notify("تم تحديث العمولة.","success");await reload()}catch(e){notify(errorText(e),"error")}}}>حفظ العمولة</button><p className="text-xs text-stone-500">تؤثر على قيود الرحلات المشتركة الجديدة فقط.</p></article>;
}
function Ledger({session,notify,reload}:{session:Session;notify:(text:string,tone?:"success"|"error"|"info")=>void;reload:()=>Promise<void>}) {
 const [kind,setKind]=useState("pool"),[trip,setTrip]=useState(""),[member,setMember]=useState(""),[amount,setAmount]=useState(""),[reason,setReason]=useState("");
 return <article className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4"><h3 className="text-lg font-bold">تسوية دفترية يدوية</h3><select className={field} value={kind} onChange={e=>setKind(e.target.value)}><option value="pool">رحلة مجموعة</option><option value="daily">رحلة يومية</option></select><input className={field} placeholder="رقم الرحلة" value={trip} onChange={e=>setTrip(e.target.value)}/><input className={field} placeholder="رقم العضو (اختياري)" value={member} onChange={e=>setMember(e.target.value)}/><input className={field} type="number" step="0.01" placeholder="المبلغ موجب أو سالب" value={amount} onChange={e=>setAmount(e.target.value)}/><textarea className={field} placeholder="السبب" value={reason} onChange={e=>setReason(e.target.value)}/><button className="rounded-lg border border-[#EAB308] px-4 py-2 font-bold text-[#EAB308]" onClick={async()=>{try{await api("/admin/ledger/adjustments",{token:session.token,method:"POST",body:{trip_kind:kind,trip_id:Number(trip),member_id:member?Number(member):null,amount:Number(amount),reason}});notify("تم تسجيل التسوية.","success");setReason("");await reload()}catch(e){notify(errorText(e),"error")}}}>تسجيل التسوية</button></article>;
}
function Pricing({row,token,pool=false,notify,reload}:{row:Row;token:string;pool?:boolean;notify:(text:string,tone?:"success"|"error"|"info")=>void;reload:()=>Promise<void>}) {
 const [values,setValues]=useState({base_fee:String(row.base_fee),rate_per_km:String(row.rate_per_km),rate_per_min:String(row.rate_per_min)});
 return <form className="grid gap-2 border-t border-stone-800 pt-3 sm:grid-cols-5" onSubmit={async(e)=>{e.preventDefault();const reason=window.prompt("سبب تعديل التسعير");if(!reason?.trim())return;const path=pool?"/admin/settings/pool-categories/"+row.vehicle_type_id:"/admin/pricing/"+row.vehicle_type_id;try{await api(path,{token,method:"PATCH",body:{...Object.fromEntries(Object.entries(values).map(([k,v])=>[k,Number(v)])),reason}});notify("تم تحديث التسعير.","success");await reload()}catch(error){notify(errorText(error),"error")}}}><strong className="self-center">{row.label||row.vehicle?.name||row.vehicle_type_id}</strong>{(["base_fee","rate_per_km","rate_per_min"] as const).map((k)=><label key={k} className="text-xs text-stone-400">{k==="base_fee"?"الأساس":k==="rate_per_km"?"لكل كم":"لكل دقيقة"}<input className={field+" mt-1"} type="number" min="0" step="0.01" value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})}/></label>)}<button className="rounded-lg border border-[#EAB308] px-3 py-2 text-[#EAB308]">حفظ</button></form>;
}
function AdminStatus({ status }: { status: string }) {
 const normalized = status.toLowerCase();
 const labels: Record<string,string> = { active:"نشط", approved:"معتمد", completed:"مكتملة", in_progress:"جارية", assigned:"مسندة", waiting:"بانتظار الركاب", pending:"قيد المراجعة", needs_captain:"بانتظار كابتن", price_review:"مراجعة السعر", rejected:"مرفوض", cancelled:"ملغاة", banned:"محظور", suspended:"موقوف" };
 const tone = ["active","approved","completed"].includes(normalized) ? "success" : ["rejected","cancelled","banned","suspended"].includes(normalized) ? "danger" : ["in_progress","assigned"].includes(normalized) ? "info" : "warning";
 return <span className={`admin-status-pill is-${tone}`}>{labels[normalized] ?? status.replaceAll("_", " ")}</span>;
}
function Empty({text}:{text:string}) { return <p className="rounded-xl border border-dashed border-stone-800 p-8 text-center text-stone-400">{text}</p>; }
function VerificationQueue({documents,loading,loadError,session,notify,refresh}:{documents:Row[];loading:boolean;loadError:string;session:Session;notify:(text:string,tone?:Toast["tone"])=>void;refresh:()=>Promise<void>}) {
 const [status,setStatus]=useState("pending");
 const [webhookBusy,setWebhookBusy]=useState(false);
 const visible=documents.filter((doc)=>status==="all"||doc.status===status);
 const registerTelegramWebhook=async()=>{setWebhookBusy(true);try{await api("/admin/verification/telegram-webhook",{method:"POST",token:session.token});notify("تم ربط بوت تيليجرام لاستقبال عمليات التحقق.","success")}catch(error){notify(errorText(error),"error")}finally{setWebhookBusy(false)}};
 return <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><label className="text-sm text-stone-400">تصفية المستندات<select className={field+" mr-2"} value={status} onChange={(event)=>setStatus(event.target.value)}><option value="pending">بانتظار المراجعة</option><option value="approved">مقبولة</option><option value="rejected">مرفوضة</option><option value="all">كل المستندات</option></select></label><div className="flex flex-wrap items-center gap-3"><span className="text-sm text-stone-500">{visible.length} مستند</span><button type="button" disabled={loading} className="rounded-lg border border-stone-700 px-3 py-2 text-sm text-stone-200 disabled:opacity-50" onClick={()=>void refresh()}>{loading?"جارٍ التحديث…":"تحديث المستندات ↻"}</button><button type="button" disabled={webhookBusy} className="rounded-lg border border-[#EAB308] px-3 py-2 text-sm text-[#EAB308] disabled:opacity-50" onClick={()=>void registerTelegramWebhook()}>{webhookBusy?"جارٍ ربط تيليجرام…":"إعداد تحقق تيليجرام"}</button></div></div>{visible.map((doc)=> <VerificationReviewCard key={doc.id} row={doc} session={session} notify={notify} refresh={refresh}/>)}{!visible.length && !loading && !loadError && <Empty text={status==="pending"?"لا توجد مستندات بانتظار المراجعة.":"لا توجد مستندات في هذه القائمة."}/>}</div>;
}
function VerificationReviewCard({row,session,notify,refresh}:{row:Row;session:Session;notify:(text:string,tone?:Toast["tone"])=>void;refresh:()=>Promise<void>}) {
 const [reason,setReason]=useState("");const [busy,setBusy]=useState(false);
 const review=async(status:"approved"|"rejected")=>{if(status==="rejected"&&reason.trim().length<3)return;setBusy(true);try{await api(`/admin/verifications/${row.id}/review`,{method:"POST",token:session.token,body:{status,...(status==="rejected"?{reason:reason.trim()}: {})}});notify(status==="approved"?"تم قبول المستند وتسجيل القرار.":"تم رفض المستند وإبلاغ المستخدم.","success");await refresh()}catch(error){notify(errorText(error),"error")}finally{setBusy(false)}};
 const openDocument=async()=>{const newTab=window.open("about:blank","_blank");if(!newTab){notify("اسمح بفتح نافذة جديدة لمعاينة المستند.","info");return}newTab.opener=null;try{const {signed_url}=await api<{signed_url:string}>(`/admin/verifications/${row.id}/file`,{token:session.token});newTab.location.replace(signed_url)}catch(error){newTab.close();notify(errorText(error),"error")}};
 return <article className="space-y-3 rounded-2xl border border-stone-800 bg-[#181818] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-lg">{row.document_label}</strong><p className="text-sm text-stone-400">{row.user?.full_name} · {row.user?.phone_number} · {row.user?.role===`captain`?"كابتن":"راكب"} #{row.user_id}</p><p className="text-xs text-stone-500">رفع في {new Date(row.uploaded_at).toLocaleString("ar-EG")}</p></div><button disabled={busy} className="rounded-lg border border-stone-700 px-3 py-2 text-sm hover:border-[#EAB308]" onClick={()=>void openDocument()}>معاينة المستند ↗</button></div><textarea className={field} rows={2} value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="سبب الرفض — مطلوب عند رفض المستند"/><div className="flex flex-wrap gap-2"><button disabled={busy} className="admin-primary rounded-lg bg-[#EAB308] px-4 py-2 font-bold text-black disabled:opacity-50" onClick={()=>void review("approved")}>اعتماد المستند</button><button disabled={busy||reason.trim().length<3} className="rounded-lg border border-red-900 px-4 py-2 text-red-300 disabled:opacity-40" onClick={()=>void review("rejected")}>رفض مع السبب</button></div></article>;
}

